name:                neXtWM
version:             0.1.0.0
github:              "githubuser/neXtWM"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/neXtWM#readme>

dependencies:
- base >= 4.7 && < 5
- classy-prelude
- X11
- text
- process
- dhall
- vector
- recursion-schemes
- free
- comonad
- deriving-compat
- containers
- polysemy
- polysemy-plugin
- QuickCheck
- generic-arbitrary
- quickcheck-instances
- chunked-data

library:
  source-dirs: src
  ghc-options:
  - -Weverything
  - -Wno-implicit-prelude
  - -Wno-missing-exported-signatures
  - -Wno-missing-import-lists
  - -Wno-missed-specialisations
  - -Wno-all-missed-specialisations
  - -Wno-unsafe
  - -Wno-safe
  - -Wno-missing-local-signatures
  - -Wno-monomorphism-restriction
  - -Wno-missing-export-lists
  - -Wno-partial-type-signatures
  - -j
  - +RTS
  - -A128m
  - -n2m
  - -RTS
  - -fplugin=Polysemy.Plugin
  default-extensions:
    - DataKinds
    - FlexibleContexts
    - GADTs
    - LambdaCase
    - PolyKinds
    - RankNTypes
    - ScopedTypeVariables
    - TypeApplications
    - TypeOperators
    - TypeFamilies
    - NoImplicitPrelude
    - BlockArguments

executables:
  neXtWM-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    dependencies:
    - neXtWM

tests:
  neXtWM-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - neXtWM
